@baseUrl = http://localhost:3000

# @name adminLogin
POST {{baseUrl}}/api/login
Content-Type: application/json; charset=utf-8

{
  "email": "admin@admin.com",
  "password": "Admin_1234"
}

###
@adminAccessToken = {{adminLogin.response.body.$.accessToken}}

###

# @name allUser
GET {{baseUrl}}/api/users
Authorization: Bearer {{adminAccessToken}}

###

# @name getUser
GET {{baseUrl}}/api/users/2
Authorization: Bearer {{adminAccessToken}}

###

# @name createUser
POST {{baseUrl}}/api/users
Authorization: Bearer {{adminAccessToken}}
Content-Type: application/json; charset=utf-8

{
  "email": "test2@example.com",
  "password": "Test_12345"
}

###

# @name updateUser
PUT {{baseUrl}}/api/users/2
Authorization: Bearer {{adminAccessToken}}
Content-Type: application/json; charset=utf-8

{
  "email": "test1@example.com",
  "firstName": "Test",
  "lastName": "Test",
  "password": "Test_12345",
  "role": "USER"
}

###

# @name updateUserRole
PUT {{baseUrl}}/api/users/3
Authorization: Bearer {{adminAccessToken}}
Content-Type: application/json; charset=utf-8

{
  "email": "test3@example.com",
  "role": "ADMIN"
}

###

# @name deleteUser
DELETE {{baseUrl}}/api/users/4
Authorization: Bearer {{adminAccessToken}}

###

# @name userLogin
POST {{baseUrl}}/api/login
Content-Type: application/json; charset=utf-8

{
  "email": "test1@example.com",
  "password": "Test_12345"
}

###
@userAccessToken = {{userLogin.response.body.$.accessToken}}

###

# @name allUser
GET {{baseUrl}}/api/users
Authorization: Bearer {{userAccessToken}}

###

# @name allUser
GET {{baseUrl}}/api/users/profile
Authorization: Bearer {{userAccessToken}}

###

# @name updateUser
PUT {{baseUrl}}/api/users/profile
Authorization: Bearer {{userAccessToken}}
Content-Type: application/json; charset=utf-8

{
  "email": "test2@example.com",
  "firstName": "Test",
  "lastName": "Test",
  "role": "ADMIN"
}

###

# @name uploadPicture
POST {{baseUrl}}/api/files/upload
Authorization: Bearer {{userAccessToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="picture"; filename="profile.png"
Content-Type: image/png

< ./pictures/profile.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
