version: '3.9'  
services:  
  db:  
    container_name: pg_container  
    image: postgres  
    restart: always  
    environment:  
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: root  
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:  
      - "5432:5432"  
    networks:
      - postgres
  pgadmin:  
    container_name: pgadmin_container  
    image: dpage/pgadmin4  
    restart: always  
    environment:  
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:  
      - "5050:80"
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
volumes:
  postgres:
  pgadmin: